version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_arlinggacr_betest
      - JWT_SECRET=test-code
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_arlinggacr_betest

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
